### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by mpash** [nilportugues/laravel5-jsonapi#113]
Project has been abandoned by the owner.

**Comment by kc22033** [comment]
Anybody aware of good alternatives? This solved a problem & sad to see it abandoned.

**Comment by MurciaFrontend** [comment]
@kc22033 I had to include a new version of our API that implements JSON API in Laravel 5.3. As I saw this project deprecated I decided to use an implementation of JSON API that is framework agnostic: https://github.com/neomerx/json-api

**Comment by Luisetelo** [comment]
@kc22033 I had to include a new version of our API that implements JSON API in Laravel 5.3. As I saw this project deprecated I decided to use an implementation of JSON API that is framework agnostic: https://github.com/neomerx/json-api

**Comment by 60days** [comment]
Thanks @Luisetelo . Did you have any issues transitioning over? There seems to be a reference implementation in Laravel here https://github.com/InactiveProjects/limoncello-collins/ but it may be out of date.

**Comment by Luisetelo** [comment]
Hi @60days, as you probably know, you need two operations, encoding and decoding to send and receive requests in JSON API format. That library offers you an encoder, but you need to create your own decoder which can be big issue (it has some, but are very simple). Futher reading [here](https://github.com/neomerx/json-api/issues/120). That is for me the main drawback.

**Comment by nilportugues** [comment]
Not abandoned... just saying.

**Comment by mpash** [comment]
@nilportugues It has been half a year.

**Comment by nilportugues** [comment]
@mpash this project is being used in production by companies and are happy with it. So please, stop bitching.

If you found a bug, provide an issue and a PR fixing it. Or at least data to reproduce the bug.
