### ISSUE TITLE
Test won't pass using Laravel 5.2

### ISSUE THREAD

**Issue by nilportugues** [nilportugues/laravel5-jsonapi#14]
See https://travis-ci.org/nilportugues/laravel5-jsonapi/jobs/98958324

**Comment by nilopc** [comment]
Seems like some internals have changed, so test-case needs to be reworked..bummer.

Yet application is compatible with Laravel 5.2. Will fix eventually... PR with fix would be cool.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/commit/f22a5288f7f6e658e7686959467ce5602534a3df
