### ISSUE TITLE
Error thrown with example code using Laravel 5.2

### ISSUE THREAD

**Issue by jonphipps** [nilportugues/laravel5-jsonapi#15]
I've implemented the code provided in the readme, and it fails under 5.2:
```
Illuminate \ Routing \ Exceptions \ UrlGenerationException
Missing required parameters for [Route: employees.show] [URI: employees/{employees}].
```
https://github.com/nilportugues/laravel5-jsonapi/blob/master/src/NilPortugues/Laravel5/JsonApi/Laravel5JsonApiServiceProvider.php#L140
```php
    private static function calculateRoute(array $value)
    {
        $route = urldecode(route($value['name']));
...
    }
```

Should return a route, but as of this commit:
https://github.com/laravel/framework/commit/cef79d827cc8024ba5c5295adff4e0efafcf4455
Laravel 5.2 checks the route for parameters and won't return the route if the required parameters are missing.
```php
        if (preg_match('/\{.*?\}/', $uri)) {
            throw UrlGenerationException::forMissingParameters($route);
        }
```

This looks like it _might_ take more refactoring than I'm comfortable trying in a pull request.

**Comment by nilportugues** [comment]
Yeah too bad they did happen to change more things that they actually documented they did... 

Will have to create a release specific for this.. or somehow detect which laravel version is actually being used and load data in the convinient way.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/commit/f22a5288f7f6e658e7686959467ce5602534a3df
