### ISSUE TITLE
 Illuminate\Foundation\Application not available in Lumen

### ISSUE THREAD

**Issue by apburton84** [nilportugues/laravel5-jsonapi#20]
```
FatalThrowableError in Laravel5JsonApiServiceProvider.php line 45:
Fatal error: Class 'Illuminate\Foundation\Application' not found
```

Illuminate\Foundation Does not exists in Lumen 5.1

From what I can see in Laravel5JsonApiServiceProvider::register() line 45, it is need to determine the version of Laravel.

```
$version = Application::VERSION;
```

**Comment by nilportugues** [comment]
Whoops sorry for introducing this break!

Fixing this in a matter of minutes. Thanks for pointing it out @apburton84

**Comment by apburton84** [comment]
That would be superb, thank you.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.4 should do it. 

Not at home but hey, it's was quick fix, but should work.  :)

**Comment by nilportugues** [comment]
`composer require nilportugues/laravel5-json-api:2.1.5` will work for all lumen versions.
