### ISSUE TITLE
soft delete implements force delete and runs it on a http GET

### ISSUE THREAD

**Issue by jonphipps** [nilportugues/laravel5-jsonapi#23]
At least that's what it looks like. As soon as I implement the eloquent softdelete trait in the model and do a get on the resource it's deleted rather than retrieved.

**Comment by jonphipps** [comment]
This is actually pretty serious. It looks like forceDelete is being run every time from 
```php
NilPortugues\Serializer\Drivers\Eloquent\Driver->getRelationshipAsPropertyName()
...
106                       $returned = $reflectionMethod->invoke($value);
```

**Comment by nilportugues** [comment]
I'll have a look at it

**Comment by nilportugues** [comment]
@jonphipps Please use version 1.0.4 of the nilportugues/serializer-eloquent package..By updating with composer update or forcing the package in the composer.json your problems should be solved. 

Thanks for reporting and your patience!

**Comment by nilportugues** [comment]
@jonphipps report me if your problems are solved, and I'll close this bug.

**Comment by andrewboy** [comment]
Hi!

I was that guy, who reported you last week by mail. I'm glad you fixed it! I'll try it out tomorrow! 

Thanks!

**Comment by nilportugues** [comment]
@andrewboy :+1: let me know if it works either by mail or here.

**Comment by jonphipps** [comment]
Nope.

I think line 147 needs to change from:
```php
NilPortugues\Serializer\Drivers\Eloquent\Driver->getRelationshipAsPropertyName()
...
147                     if (false === in_array($value, $this->forbiddenFunction, true)) {
```
to:
```php
NilPortugues\Serializer\Drivers\Eloquent\Driver->getRelationshipAsPropertyName()
...
147                     if (false === in_array($name, $this->forbiddenFunction, true)) {
```

**Comment by nilportugues** [comment]
@jonphipps @andrewboy Hopefully it will be fixed now. Use 1.0.5 for the `nilportugues/serializer-eloquent` package. I started adding tests for it... https://github.com/nilportugues/serializer-eloquent-driver. 

Please add more tests or try reproduce your bug there by bringing in your eloquent models there! It would be of great help and not only `laravel5-jsonapi` package would benefit but also `laravel5-haljson`.

**Comment by nilportugues** [comment]
I believe it won't happen anymore. I have fully tested `nilportugues/serializer-eloquent` and seems everything is OK. Please, report the bug there if something weird is still going on :)

I'm closing this, but feel free to comment @jonphipps @andrewboy is any issue raises.
