### ISSUE TITLE
Got problem when try to add package (symphony/http-foundation)

### ISSUE THREAD

**Issue by pnghai** [nilportugues/laravel5-jsonapi#24]
Please help, I got this error when try to install your package to my Laravel 5.2 project.

<pre>Problem 1
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.5
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.4
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.3
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.2
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.1
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Installation request for nilportugues/laravel5-json-api ^2.1 -> satisfiable by nilportugues/laravel5-json-api[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5].
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - nilportugues/laravel5-json-api 2.1.0 requires nilportugues/json-api 2.1.* -> satisfiable by nilportugues/json-api[2.1.0, 2.1.1, 2.1.2].
    - nilportugues/json-api 2.1.0 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - nilportugues/json-api 2.1.1 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - nilportugues/json-api 2.1.2 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - Can only install one of: symfony/http-foundation[v2.8.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.8.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.8, v3.0.1].
    - Installation request for symfony/http-foundation == 3.0.1.0 -> satisfiable by symfony/http-foundation[v3.0.1].

Installation failed, reverting ./composer.json to its original content.
</pre>

**Comment by nilportugues** [comment]
I'll have a look at this. Should be easy to solve. Let's find the dependency... or set an alternative version for the dependency causing the conflict

**Comment by nilportugues** [comment]
@pnghai I can't seem to be able to reproduce your bug at all. I tried pulling the repository with the dependency using the following `composer.json` file and no problems occurred.

```
{
    "require": {
        "nilportugues/json-api": "2.1.3",
        "nilportugues/serializer-eloquent": "~1.0",
        "symfony/psr-http-message-bridge": "~0.1",
        "laravel/laravel": "5.2.*"
    }
}
```

Mind sharing your dependencies?

**Comment by wlepinski** [comment]
Same error here.
I think the problem is here:
`nilportugues/json-api 2.1.0 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].`

**Comment by wlepinski** [comment]
Adding `"nilportugues/laravel5-json-api": "dev-master"` on package.json worked for me.

**Comment by nilportugues** [comment]
ooh, 2.1.0 ... well, time for you all to update to 2.1.5... @wlepinski @pnghai.

While I keep dev-master stable 99.9% percent of the time, it's better if you all use a stable version.

**Comment by wlepinski** [comment]
@nilportugues The thing is that I just did a `$ composer require nilportugues/laravel5-json-api` and for some reason  the package on laravel5-json-api asks for a nilportugues/json-api: ~2.1, composer them used the version 2.1.0 instead of 2.1.3 that is your latest version deployed on Packagist (https://packagist.org/packages/nilportugues/json-api).

Maybe you need to put ^2.1.* as the required version range for `nilportugues/json-api`?

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.7

**Comment by nilportugues** [comment]
@wlepinski @pnghai let me know if 2.1.7 solves this... or send me a PR to any of the libraries involved that I manage :)

**Comment by pnghai** [comment]
I use "nilportugues/laravel5-json-api": "2.1.*" with your 2.1.8 version and thing works well.

I noticed that the error occur when I just use the automatic-version-detection command ("composer require nilportugues/laravel5-json-api"), below is the error:

<pre>
require nilportugues/laravel5-json-api
Using version ^2.1 for nilportugues/laravel5-json-api
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install nilportugues/json-api 2.1.3
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.8
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.7
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.6
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.5
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.4
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.3
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.2
    - Conclusion: don't install nilportugues/laravel5-json-api 2.1.1
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Installation request for symfony/console == 3.0.1.0 -> satisfiable by symfony/console[v3.0.1].
    - Installation request for nilportugues/laravel5-json-api ^2.1 -> satisfiable by nilportugues/laravel5-json-api[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8].
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - nilportugues/laravel5-json-api 2.1.0 requires nilportugues/json-api 2.1.* -> satisfiable by nilportugues/json-api[2.1.0, 2.1.1, 2.1.2, 2.1.3].
    - nilportugues/json-api 2.1.0 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - nilportugues/json-api 2.1.1 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - nilportugues/json-api 2.1.2 requires symfony/http-foundation ^2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.8.0, v2.8.1].
    - Can only install one of: symfony/http-foundation[v2.8.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.8.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.0, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.1, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.2, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.3, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.4, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.5, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.6, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.7, v3.0.1].
    - Can only install one of: symfony/http-foundation[v2.7.8, v3.0.1].
    - Installation request for symfony/http-foundation == 3.0.1.0 -> satisfiable by symfony/http-foundation[v3.0.1].


Installation failed, reverting ./composer.json to its original content.
</pre>

Thank for your attention :)

**Comment by nilportugues** [comment]
Sounds like it's because of your composer cache... `COMPOSER_CACHE_DIR=/dev/null composer update` should do the trick

It's a composer issue then. :)
