### ISSUE TITLE
Inclusion with belongsTo relationship

### ISSUE THREAD

**Issue by pnghai** [nilportugues/laravel5-jsonapi#25]
Hi there,

I have a property which belongs to another model (belongsTo relationship), how can I implement to include it in the inclusion part of json?

For example: just take your default example, is there anyway to show the employee information in the inclusion part of order result? (the opposite direction of your default example.)

**Comment by pnghai** [comment]
Hi there,

I figure it out that your line to extract result and convert to a proper model is lack of treating the return value as a single object:

Path: \nilportugues\serializer-eloquent\src\Helper\RelationshipPropertyExtractor.php
```php
if (\is_object($returned)) {
// Only keep those methods as properties if these are returning Eloquent relations.
                                // But do not run the operation as it is an expensive operation.
                                if (self::isAnEloquentRelation($returned)) {
                                    $items = [];
                                    $temp = $returned->getResults(); //be aware that there may be a single result. Can we use some eager load?
                                    if (is_array($temp)):
                                        foreach ($temp as $model) {
                                            if (\is_object($model)) {
                                                $items[] = self::getModelData($serializer, $model);
                                            }
                                        }
                                    else:
                                        if (\is_object($temp)) {
                                            $items[] = self::getModelData($serializer, $temp);
                                        }
                                    endif;

**Comment by nilportugues** [comment]
I'll test it and update the library if that's the case.

**Comment by nilportugues** [comment]
Added to https://github.com/nilportugues/serializer-eloquent-driver @pnghai. 

Could you help me coding the remaining examples listed in the serializer-eloquent-driver to spot any missing cases?

**Comment by pnghai** [comment]
Sorry, I check your response late. I'd check your remaining examples this weekend.

Regards,
