### ISSUE TITLE
loss of default page size

### ISSUE THREAD

**Issue by apburton84** [nilportugues/laravel5-jsonapi#26]
$apiRequest = RequestFactory::create(); 
    $page = $apiRequest->getPage();

    if (! $page->size()) {
        $page->setSize(5); // Default elements per page
    }

When using the above code at the top of a controller action, as is done in the example in the README.

After calling EloquentHelper::paginate() the $page->size() returns null.

I believe this to be caused by the fact that $page is not a singleton like Request, as in Request::getPage() a new Page() object is created based of the query parameters.

    $page = new Page(
       (!empty($queryParam['number'])) ? $queryParam['number'] : 1,
       (!empty($queryParam['cursor'])) ? $queryParam['cursor'] : null,
       (!empty($queryParam['limit'])) ? $queryParam['limit'] : null,
       (!empty($queryParam['offset'])) ? $queryParam['offset'] : null,
       (!empty($queryParam['size'])) ? $queryParam['size'] : null
    );

**Comment by nilportugues** [comment]
Today I actually solved this bug, as someone else spotted the error at https://github.com/nilportugues/php-json-api/commit/1c955b9297075ad298c9e58427e47e729d9e4bf4

Try updating the dependency and it will be automagically fixed. 

Thanks for reporting :)

**Comment by apburton84** [comment]
This does not resolve the issue, it just defaults the page_size to 10, it does not let the end user specify a default.

**Comment by nilportugues** [comment]
@apburton84  OK, I'll fix this and allow customization using a `protected $pageSize` class property. Give me some minutes :)

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/commit/7644cb84b41088a99bf3ef31e597841dd8ff47b9 :+1: 

https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.9

**Comment by apburton84** [comment]
Looks good, I will test first thing in the morning. Thanks

**Comment by nilportugues** [comment]
@apburton84 glad I could help. Let me know if you find anything else that needs fixing/ajusting

**Comment by apburton84** [comment]
@nilportugues Unfortunately setting $pageSize in a controller does not alter the page size.

I have the following in my controller
    
    protected $pageSize = 20;

The problem is here

https://github.com/nilportugues/php-json-api/blob/master/src/Http/Request/Request.php

    /**
     * @return \NilPortugues\Api\JsonApi\Http\Request\Parameters\Page
     */
    public function getPage()
    {
        $queryParam = $this->getQueryParam('page');
        $page = new Page(
            (!empty($queryParam['number'])) ? $queryParam['number'] : 1,
            (!empty($queryParam['cursor'])) ? $queryParam['cursor'] : null,
            (!empty($queryParam['limit'])) ? $queryParam['limit'] : null,
            (!empty($queryParam['offset'])) ? $queryParam['offset'] : null,
            (!empty($queryParam['size'])) ? $queryParam['size'] : 10
        );
        return $page;
    }

More specifically this line

    (!empty($queryParam['size'])) ? $queryParam['size'] : 10

If the query parameter $_GET['Page']['size'] is not set the page size will always be 10

**Comment by nilportugues** [comment]
@apburton84 I undid the PR on the original package. It should be null there, not 10. 

Get 2.1.5 for json-api package.

**Comment by apburton84** [comment]
Hi @nilportugues 

Thanks for your time and help.

Could you confirm please that if you replace the contents of 

    public function getOrdersByEmployee(Request $request)

In the example in the README, With the following. 

        $apiRequest = RequestFactory::create();
        $page = $apiRequest->getPage();

        if (!$page->size()) {
            $page->setSize(666); //Default elements per page
        }

        echo $page->size();

        $resource = new ListResource(
            $this->serializer,
            $page,
            $apiRequest->getFields(),
            $apiRequest->getSort(),
            $apiRequest->getIncludedRelationships(),
            $apiRequest->getFilters()
        );

        $totalAmount = function() use ($request) {
            $id = (new Orders())->getKeyName();
            return Orders::query()
                ->where('employee_id', '=', $request->employee_id)
                ->get([$id])
                ->count();
        };

        $results = function()  use ($request) {
            return EloquentHelper::paginate(
                $this->serializer,
                Orders::query()
                    ->where('employee_id', '=', $request->employee_id)
            )->get();
        };

        $uri = route('employees.orders', ['employee_id' => $request->employee_id]);

        $page = $apiRequest->getPage();
        echo $page->size();

        die();

Which will echo the value that will be used for the page size (I believe)

    echo $page->size(); === 666

My composer.lock file contains the following for the json-api package

           "name": "nilportugues/json-api",
            "version": "2.1.5",
            "source": {
                "type": "git",
                "url": "https://github.com/nilportugues/php-json-api.git",
                "reference": "9f32051c7742c046a36dc1a89bc1416b6f2ed454"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/nilportugues/php-json-api/zipball/9f32051c7742c046a36dc1a89bc1416b6f2ed454",
                "reference": "9f32051c7742c046a36dc1a89bc1416b6f2ed454",
                "shasum": ""
            },
            "require": {
                "nilportugues/api-transformer": "~1.5",
                "nilportugues/php_backslasher": "^0.2.1",
                "php": ">=5.5.0",
                "symfony/http-foundation": "2.*|3.*",
                "symfony/psr-http-message-bridge": "0.2"
            },
            "require-dev": {
                "fabpot/php-cs-fixer": "^1.9",
                "mmoreram/php-formatter": "dev-master",
                "phpunit/phpunit": "4.*",
                "satooshi/php-coveralls": "dev-master"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "NilPortugues\\Api\\JsonApi\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nil Portugués Calderó",
                    "email": "contact@nilportugues.com",
                    "role": "Project Lead Developer"
                }
            ],
            "description": "Serializer transformers outputting valid API responses in JSON, JSON API and HAL+JSON API formats.",
            "homepage": "http://nilportugues.com",
            "keywords": [
                "api",
                "json",
                "jsonapi",
                "psr7",
                "response",
                "serializer",
                "transformer"
            ],
            "time": "2016-01-19 11:35:05"

**Comment by nilportugues** [comment]
@apburton84 This needs investigation. I will test it out with my test application (I guess I should upload it somewhere too).

Thanks for the detailed explanation. It will help me out figuring out where it's failing to do what it's supposed to do.

**Comment by apburton84** [comment]
@nilportugues Do you have a away to donate to this project ?

**Comment by jeremymlane** [comment]
FYI, looks like the issue is that it defaults to using the model's `protected $perPage` attribute instead of the controller's `protected $pageSize` attribute. 

Take a look at line [36 of EloquentHelper.php](https://github.com/nilportugues/laravel5-jsonapi/blob/master/src/NilPortugues/Laravel5/JsonApi/Eloquent/EloquentHelper.php#L36). 

That line always passes in null unless `page[size]` has been specified in the query string. A workaround is to set `$perPage` on your model.

**Comment by gharding** [comment]
I just came here about to report this very issue. I can confirm however that the workaround proposed by @jeremymlane does work.

Cheers @jeremymlane

**Comment by apburton84** [comment]
@jeremymlane cheers!
