### ISSUE TITLE
Inclusion of relationships in data items

### ISSUE THREAD

**Issue by apburton84** [nilportugues/laravel5-jsonapi#27]
When requesting the following endpoint **/api/v1/user/1**

I would expect the relationships attribute to be present in the data section and for it to contain any related objects for each item.  However it is not.

If I request **/api/v1/user/1/client** I get the relationships returned for the client object, which is all the users associated to the client.

The only difference that I can see between the two endpoints is that in the **read** controller method **$results** is a **Builder** object and in **client** controller method **client** is a **Client** model. 
 
**route**

    $app->get('user/{id}', ['as' => 'user.get', 'uses' => "UserController@read"]);
    $app->get('user/{id}/client', ['as' => 'user.client', 'uses' => "UserController@client"]);

**Controllers**

    public function read(Request $request, $id = false)
    {
        $results = User::query();

        if ($id) {
            $results->where('id', $id);
        }

        $results = EloquentHelper::paginate($this->serializer, $results)->get();
        return $this->toJsonAPI(User::class, $results, $request);
    }

    public function client(Request $request, $id)
    {
        $user   = User::find($id);
        $client = $user->client;

        $transformer = $this->serializer->getTransformer();
        $transformer->setSelfUrl(route('user.client', ['id' => $id]));

        return $this->toJsonAPI(Client::class, $client, $request);
    }

***toJsonAPI***

    public function toJsonAPI($model_class, $results, $request)
    {
        $url = $request->url();

        $results = function () use ($results) {
            return $results;
        };

        $total = function () use ($results) {
            return $results()->count();
        };

        $api_request = RequestFactory::create();

        $page_size = $this->page_size;
        $page      = $api_request->getPage();

        if (! $page->size()) {
            $page->setSize($page_size);
        }

        $fields    = $api_request->getFields();
        $sorting   = $api_request->getSort();
        $included  = $api_request->getIncludedRelationships();
        $filters   = $api_request->getFilters();

        $resource = new ListResource($this->serializer, $page, $fields, $sorting, $included, $filters);

        return $resource->get($total, $results, $url, $model_class);
    }

**Comment by apburton84** [comment]
I believe the issue the problem is in https://github.com/nilportugues/serializer-eloquent-driver/blob/master/src/Helper/RelationshipPropertyExtractor.php

The if statement on line 89 will always fall into the first clause, if the clause are reversed relationships are returned.

**Comment by apburton84** [comment]
This issue is related https://github.com/nilportugues/laravel5-jsonapi/issues/25

**Comment by nilportugues** [comment]
@apburton84 try doing a composer update for the eloquent serializer. There have been fixes today. These may solve your problem.

I haven't checked this issue yet. Thanks for your patience

**Comment by apburton84** [comment]
@nilportugues Yes, this does resolve the issue, thank you

**Comment by nilportugues** [comment]
Great! I'm closing this bug then!
