### ISSUE TITLE
php artisan vendor:publish error

### ISSUE THREAD

**Issue by andrewboy** [nilportugues/laravel5-jsonapi#30]
After I set the package, on vendor:publish I get this error message:

[ErrorException]
mkdir(): Invalid path

**Comment by nilportugues** [comment]
Clearly a bug. 

Do it manually, while I fix this if you don't mind.

**Comment by obayesshelton** [comment]
Any news on this bug?

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.12 :)

**Comment by obayesshelton** [comment]
Thanks :)

**Comment by TBarina** [comment]
I still have this problem in Laravel 5.2.

My composer shows:
  nilportugues/api-transformer             1.5.0 
  nilportugues/json-api                        2.1.7 
  nilportugues/laravel5-json-api           2.1.12 
  nilportugues/serializer                     1.1.10
  nilportugues/serializer-eloquent         1.0.9  

How can I fix?
Many thanks in advance.

**Comment by nilportugues** [comment]
@TBarina let me look into it

**Comment by nilportugues** [comment]
@TBarina https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.15

**Comment by TBarina** [comment]
Many thanks. It works perfectly now.
