### ISSUE TITLE
Client-Generated ID

### ISSUE THREAD

**Issue by andrewboy** [nilportugues/laravel5-jsonapi#31]
Hi!

When I want to store a model with a pre-defined ID, in the JsonApiController class createResourceCallable method

            if (!empty($data['id'])) {
                $model->setAttribute($model->getKeyName(), $values['id']);
            }

I think the $values['id'] have to be $data['id'].

**Comment by nilportugues** [comment]
Tagging as bug for the time being. 

Need to investigate. Will write a test and see if i can reproduce this.

**Comment by floh1111** [comment]
I encountered the same problem and looked at the spec at http://jsonapi.org/format/#crud-creating

Looks like @andrewboy is right. I will make a merge request :)
