### ISSUE TITLE
Can't figure out the file names and their paths

### ISSUE THREAD

**Issue by tenzan** [nilportugues/laravel5-jsonapi#33]
Hi, I'm at the `EmployeesTransformer` section now.

It says:
> Follow up, we'll be creating Transformers. One Transformer is required for each class and it must implement the `\NilPortugues\Api\Mappings\JsonApiMapping interface`.

1. Can you please tell me where in the app and what file name should I create for the code snippet you showed there?

2. And when you say `Employees (Eloquent Model)`, is it `Employees.php` under `app/Models`?

It'd be easier to follow for newbies if you provide with file names and their paths, so that it'll be easier to learn.

Thanks for your efforts.

**Comment by nilportugues** [comment]
You can create this file anywhere. I would just create a directory for it, close to your models or controllers directory.

Yes, Eloquent Model refers to app/Models/Employee.php. Any recomendation or suggestion for better wording in the README?

**Comment by tenzan** [comment]
Yeah, sure. For example, `README.md` file has:

> This is how our app/Http/routes.php will look:

```
<?php
Route::group(['namespace' => 'Api'], function() {
    Route::resource('employees', 'EmployeesController');    
    Route::get(
        'employees/{employee_id}/orders', [
        'as' => 'employees.orders',
        'uses' => 'EmployeesController@getOrdersByEmployee'
    ]);
});
```

Here I clearly see that the file name is `routes.php` and it's located in the `app/Http/`.
Such way, it's quite easy to follow the instructions... ;)

**Comment by nilportugues** [comment]
@tenzan :+1: added more explicit placement of the Transformer files in the readme. 

Open a new issue if more accurate explanations are required in any part. 

Thanks!

**Comment by tenzan** [comment]
:+1
