### ISSUE TITLE
All relationships are automatically added to included

### ISSUE THREAD

**Issue by directrix1** [nilportugues/laravel5-jsonapi#38]
The included section automatically adds any resources listed in a relationship of the primary data. This should be optional.

**Comment by nilportugues** [comment]
The only way to do this optionally is to define another object and do not set or set the data there...it was done on purpose for 1.0.0

If I was to implement this and make it configurable, how would you approach it? I mean, using the configuration file. 

There's plenty of cases to make this "optional" value true or false, for example... if a certain attribute matches a value, or if it's parent class is A, or B, or implements interface X.

... just wondering. It can really get complex.

**Comment by directrix1** [comment]
Maybe add another method to the JsonApiMapping interface:
```
/**
 * Returns a list of relationships whose resources you wish to include in the included section.
 *
 * @return array
 */
public function getDefaultIncluded() {
          return ['relationship1', 'relationship2', 'relationship3'];
}
```

**Comment by nilportugues** [comment]
I'm unsure this is actually something I should allow, as there's the `include` query param to decide which to include defined in the standard.

**Comment by directrix1** [comment]
Yeah, but what I'm talking about is just what is included by default, as the spec mentions this being vendor specific. 

> An endpoint MAY return resources related to the primary data by default.

 When the include query param is included getDefaultIncluded should be totally ignored.

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

**Comment by samgreenwood** [comment]
I've done some digging and found that the serializer-eloquent package serializes all relationships on the model, fetching them causing quite a bit of slowness, from what I can tell this is also what is causing relationships to always show in 'included' regardless if they're specified or not.

https://github.com/nilportugues/serializer-eloquent-driver/blob/master/src/Driver.php#L98-L103

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.2.0
