### ISSUE TITLE
Previous page not setting in pagination on page 2

### ISSUE THREAD

**Issue by gharding** [nilportugues/laravel5-jsonapi#44]
The pagination links in the returned JSON API response include the previous link on all pages except for pages 1 and 2. This is understandable and correct for page 1, however page 2 should have a previous page included.

Having looked through the code I can see on line 179 of json-api/src/Server/Actions/ListResource.php that the previous page number is set if the value is greater than 1:

`'previous' => ($previous > 1) ? $previous : null,`

To fix this issue the operator should be changed from `>` to `>=`

**Comment by apburton84** [comment]
This is actually in https://github.com/nilportugues/php-json-api, I have create a pull request to resolve https://github.com/nilportugues/php-json-api/pull/52

**Comment by apburton84** [comment]
I believe this issue has now been resolved @nilportugues @gharding
