### ISSUE TITLE
Unable to get serializer in Controller working

### ISSUE THREAD

**Issue by jonaholsson** [nilportugues/laravel5-jsonapi#45]
I have extended my controller to LumenJsonApiController, but I'm not getting the Serializer (NULL). All output from the controller is untouched json when doing `return $results` or similar from my methods. What am I doing wrong?

**Comment by jonaholsson** [comment]
Problem solved. I realized I forgot to remove a `__construct()` function in my Controller which override the JsonApi controller.

**Comment by nilportugues** [comment]
Glad you solved it. :+1:
