### ISSUE TITLE
Simplified models

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#48]
Instead of returning models with their relationships, I would like to return them with their related properties instead. For instance, let's say I have this database structure:

```
users
- id
- name
- group_id

user_groups
- id
- name

user_notes
- user_id
- text
```
I would want to return this as the user attributes:
```
       {
        "id": 1,
        "name": "Some name",
        "group": "Some group name",
        "user_notes": {
              "First note text",
              "Second note text"
         }
       },
```
How can I approach this?

**Comment by nilportugues** [comment]
**Option 1**
Fetch data as normal, create a new object to represent data as you want and use the mapping (same as if it was an eloquent model) tol serialize as you like. 

**Option 2**
Write the SQL for the query (JOIN) and serialize the resulting object (stdClass)

**Option 3**
Write a [SQL VIEW](http://www.tutorialspoint.com/sql/sql-using-views.htm) and create a new Eloquent model class that reads from that view.

Either should do it. I believe, from your point of view (proposing tables) going for the VIEW would fit your needs best.

**Comment by OskarD** [comment]
Thank you for a great answer!

However, options 2 and 3 would not support the one-to-many relationship (user_notes), right? So my only option is 1?

**Comment by nilportugues** [comment]
You can write relationships based on your view...  so option 1 and 3.

**Comment by OskarD** [comment]
I am not sure I understand... Do you mean a mix of option 1 and 3?

**Comment by nilportugues** [comment]
You can create a view, and then create a new eloquent model to map to that view... and code the relationships you need to show.

**Comment by OskarD** [comment]
So a view like this:
`CREATE VIEW special_users AS
SELECT users.id, users.name, user_groups.name
FROM users
LEFT JOIN user_groups ON users.group_id = user_groups.id`

And then code the SpecialUser class with the relationship like normal? That would not be enough to make a fully "simplified" model :/

**Comment by OskarD** [comment]
I figured out what you meant. It can be done using the 'appends'-variable and declaring a `getSomethingAttrubute` function :) Thanks!
