### ISSUE TITLE
Undefined index: [Random relation]

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#50]
I am getting this error when listing my resource:
```
object(ErrorException)[155]
  protected 'message' => string 'Undefined index: App\Party\Group' (length=32)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '/home/vagrant/parties/api/vendor/nilportugues/json-api/src/Helpers/DataLinksHelper.php' (length=86)
  protected 'line' => int 107
...
```

`App\Party\Group` is a model related to the listed resource, which is `App\Party\Party`.

I tried clearing my cache etc. and it seems like the undefined index is different every time. It it always the classname of one of the listed resource's relations. The index (The `$mappings` variable) only contains the classname of the listed resource, `App\Party\Party`.

I don't understand why this error occurs, so I don't know how to fix it. I've made sure all my relations work as they should, so it doesn't seem to be that.

**Comment by nilportugues** [comment]
@OskarD Mind sharing the table schema/s? 

All I can think of is a bug on the underling json-api package... setting up relationships wrong for some case I didn't take into accound.

**Comment by OskarD** [comment]
I don't know what happened between then and now, but now I get a different error. I didn't, as far as I can remember, change my code and I am pretty sure it didn't change with the 2.1.15 update.

> FatalThrowableError in MappingFactory.php line 36:
> 
> Fatal error: Cannot instantiate abstract class Illuminate\Database\Eloquent\Model
> 
> in MappingFactory.php line 36
> 
> at ReflectionClass->newInstanceWithoutConstructor() in MappingFactory.php line 36
> 
> at MappingFactory::getClassProperties('Illuminate\Database\Eloquent\Model') in 
> MappingFactory.php line 206
> 
> at MappingFactory::getClassProperties('App\Party\Party') in MappingFactory.php line 45
> 
> at MappingFactory::getClassProperties('App\Party\Party') in MappingFactory.php line 287
> 
> at MappingFactory::setProperties(object(Mapping), 'App\Party\Party') in MappingFactory.php line 104

**Comment by OskarD** [comment]
...and now it's back to the original error. I have absolutely no idea what is happening.

**Comment by OskarD** [comment]
@nilportugues is there anything I can do to troubleshoot?

**Comment by OskarD** [comment]
@nilportugues if there is nothing that can be done about this, I will have to convert my whole project to Laravel. Is there anything I can do to help you with this?

**Comment by nilportugues** [comment]
I can see a bug there... in the original lib. I can fix this exception.

**Comment by nilportugues** [comment]
@OskarD to benefit from this fix do a composer update. `nilportugues/php-json-api@2.1.9` should come in.

**Comment by nilportugues** [comment]
@OskarD let me know if this clears up your bug or not so I can close this issue.

**Comment by OskarD** [comment]
@nilportugues I think it solved the problem, thank you so much!

**Comment by OskarD** [comment]
It reappeared when I tried to do this:

`return $resource->get($totalAmount, $results, $uri, Property::class);`
```
protected 'message' => string 'Undefined index: App\Party\Property\Property' (length=44)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '/home/vagrant/parties/api/vendor/nilportugues/json-api/src/Helpers/DataLinksHelper.php' (length=86)
  protected 'line' => int 263

```

**Comment by nilportugues** [comment]
Go for a composer update. I covered all cases in release 2.1.10

**Comment by OskarD** [comment]
It works! Thanks again!!!

**Comment by nilportugues** [comment]
@OskarD thanks for helping cleaning out the hard edges :+1:
