### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by andreipokotskiy** [nilportugues/laravel5-jsonapi#51]
on get request:
NilPortugues\Api\Mapping\MappingFactory::fromArray() must be of the type array, string given .....

**Comment by nilportugues** [comment]
True... change employees.get to employees.show for `OrdersTransformer`. 

Thanks for the heads up.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/commit/141c47dc75a1d7d16f8c70466104fdda70c9ad16
