### ISSUE TITLE
Api ignores base route in href

### ISSUE THREAD

**Issue by philippkratzer** [nilportugues/laravel5-jsonapi#53]
Hello,

I have a setup with an alias (in my case: http://localhost/testproject) to my laravel public directory.

Here is the example of the readme.md (omployee, orders example). This generates wrong links in href, like:
```
"links": {
        "self": {
          "href": "http://localhost/employees/1"
        },
        "employee_orders": {
          "href": "http://localhost/employees/1/orders"
        }
      }
```
note that the "testproject" is missing in the link.
Interesting is, that the pagination seems to generate correct links, therefore i suspect that my setup is correct and there is a bug in the package.
The response for the pagination:
```
"links": {
    "self": {
      "href": "http://localhost/testproject/employees?page[number]=1&page[size]=10"
    },
    "first": {
      "href": "http://localhost/testproject/employees?page[number]=1&page[size]=10"
    },
    "last": {
      "href": "http://localhost/testproject/employees?page[number]=1&page[size]=10"
    }
  }
```

Thank you very much

**Comment by nilportugues** [comment]
I'll check it out tomorrow morning (midnight over here).

Keep you posted @philippkratzer

**Comment by nilportugues** [comment]
@philippkratzer https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.3.1
