### ISSUE TITLE
DataObject throws a DataException with no message

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#54]
An uncaught DataException is thrown without a message or anything in the [DataObject class](https://github.com/nilportugues/php-json-api/blob/master/src/Server/Data/DataObject.php#L62)

I know it belongs to a different repo but I thought it was relevant to this too since this is where I have encountered it. Feel free to let me know if you want me to put it on the other issue tracker.

It was thrown in my applicaton because I had removed a field from my database:

```
object(NilPortugues\Api\JsonApi\Server\Errors\ErrorBag)[39]
  protected 'errors' => 
    array (size=1)
      0 => 
        object(NilPortugues\Api\JsonApi\Server\Errors\MissingAttributeError)[58]
          protected 'id' => null
          protected 'links' => 
            array (size=0)
              ...
          protected 'status' => null
          protected 'code' => string 'unprocessable_entity' (length=20)
          protected 'title' => string 'Missing Attribute' (length=17)
          protected 'detail' => string 'Attribute `party_group_id` is missing.' (length=38)
          protected 'source' => 
            array (size=1)
              ...
          protected 'meta' => null
  protected 'httpCode' => null
```

If the error message could be relayed through the Exception, it would be easier to troubleshoot the problem

**Comment by floh1111** [comment]
I also encountered this problem and in my opinion it is a must have to tell the client in detail what has gone wrong. Therefore one should be able to pass not only a string message to the DataException but also an ErrorBag if needed.

I did some work on more simple APIs previously and in my opinion Dingos ResourceException could be used as template for implementing this: https://github.com/dingo/api/blob/master/src/Exception/ResourceException.php

If you dont mind I'll try this and make a pull request later on.

**Comment by nilportugues** [comment]
@floh1111 sure, I'm open to improvements.

Maybe it's all about creation an exception that can have this set and retrieved in the upper layers.

**Comment by nilportugues** [comment]
Will be pack in the 2.4.0 release (tomorrow) as the exception changed the constructor and adds a method

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.4.0
