### ISSUE TITLE
Incompatibility with group prefix.

### ISSUE THREAD

**Issue by marcelomarra** [nilportugues/laravel5-jsonapi#55]
Using this routes.php:

Route::group(['middleware' => ['web'], 'prefix' => 'api'], function () {
    Route::resource('/schedule', 'ScheduleController');
});

This exception is thrown: Exception in Laravel52Provider.php line 51: Provided route name does not exist

This occurs because the Laravel52Provider ignores the prefix information:
" if ($routerObject->getName() === $value['name']) { "
" if ('api.resources.show' === 'resources.show') {"

The fix that I suggest is to concatenate the prefix with "$value['name']" and return correctly the full path.

"
$prefix = str_replace('/', '.', $routerObject->getPrefix());
if ($routerObject->getName() === $prefix . $value['name']) {
"

I will submit a pull request ASAP.

**Comment by nilportugues** [comment]
Will investigate. This is clearly something that has not been taken into account in the Laravel5xProviders.

**Comment by nilportugues** [comment]
@marcelomarra this has been fixed as now `url` method is used.

https://github.com/nilportugues/laravel5-jsonapi/blob/master/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel52Provider.php#L89
