### ISSUE TITLE
Relationships and the jsonapi 1.0 standard doesn't match.

### ISSUE THREAD

**Issue by rmarinleal** [nilportugues/laravel5-jsonapi#57]
Hi,

I'm using your library in a project with Ember (and ember data) as a FrontEnd Framework , which incude a jsonapi extension.

Well, ember data parse the relationships as the standard 1.0 specification, but your library doesn't fit to it.

First off all, your library always returns the relations as an array of data objects, but the specification sais that the relationships of a model have to be a data object with as many objects (type and id) as records in the query.

Example:
laravel5-jsonapi:
`{
  "data": [
    {
      "type": "channels",
      "id": "1",
      "attributes": {
        "company_id": "1"
      },
      "links": {
        "self": {
          "href": "http://localhost:55555/channels/1"
        }
      },
      "relationships": {
        "company": [
          {
            "data": [
              {
                "type": "companies",
                "id": "1"
              }
            ]
          }
        ],
        "platforms": [
          {
            "data": [
              {
                "type": "platforms",
                "id": "1"
              }
            ]
          },
          {
            "data": [
              {
                "type": "platforms",
                "id": "1"
              },
              {
                "type": "platforms",
                "id": "2"
              }
            ]
          }
        ] ...etc etc`

instead of 

`{
  "data": [
    {
      "type": "channels",
      "id": "1",
      "attributes": {
        "company_id": "1"
      },
      "links": {
        "self": {
          "href": "http://localhost:55555/channels/1"
        }
      },
      "relationships": {
        "company": {
          "data": [
            {
              "type": "companies",
              "id": "1"
            }
          ]
        },
        "platforms": {
          "data": [
            {
              "type": "platforms",
              "id": "1"
            },
            {
              "type": "platforms",
              "id": "2"
            }
          ]
        } ...etc etc`

I will correct it in the DataLinksHelper.php file, please consider to change it.

Another problem, and bigger, is than the output of the relationships node must match with the nature of the relation, for example, if the model has a relation with belongsTo, the output always will be a property data as an object (not an array) with the type and id properties of the relation:
Example: 
`"relationships": {
        "company": {
          "data": {
            "type": "companies",
            "id": "1"
          }
        },...etc`

If the relaion is multiple record (such a hasMany) the output allwais have to be an array (also if the query only returns one object)
Example:
`{
"relationships": {
        "platforms": {
          "data": [
            {
              "type": "platforms",
              "id": "1"
            }
          ]
        }...etc`

OR
`
{"relationships": {
        "platforms": {
          "data": [
            {
              "type": "platforms",
              "id": "1"
            },
            {
              "type": "platforms",
              "id": "2"
            }
          ]
        }...etc`

You can see the specification here:
http://jsonapi.org/format/#fetching-relationships

**Comment by nilportugues** [comment]
If you've got a PR I'm willing to accept it :+1:

**Comment by OskarD** [comment]
I ran into the same problem, looking forward to your PR @rmarinleal :)

**Comment by nilportugues** [comment]
Still haven't had time... to fix it. PR would be awesome @rmarinleal

**Comment by OskarD** [comment]
The commit above only addresses the first problem described in this issue

**Comment by nilportugues** [comment]
Any fix solving issues for this is very welcomed

**Comment by nilportugues** [comment]
Late at night, but I could get in the computer. Checking it @OskarD. Will update :)

**Comment by nilportugues** [comment]
Alright. Just fix the test. Replace test with the json expected:  

```php

    /**
     *
     */
    public function testItWillSerializeToJsonApiAComplexObject()
    {
        $mappings = HelperMapping::complex();
        $mapper = new Mapper($mappings);

        $expected = <<<JSON
{
   "data":{
      "type":"post",
      "id":"9",
      "attributes":{
         "title":"Hello World",
         "content":"Your first post"
      },
      "links":{
         "self":{
            "href":"http://example.com/posts/9"
         },
         "comments":{
            "href":"http://example.com/posts/9/comments"
         }
      },
      "relationships":{
         "author":{
            "links":{
               "self":{
                  "href":"http://example.com/posts/9/relationships/author"
               },
               "related":{
                  "href":"http://example.com/posts/9/author"
               }
            },
            "data":{
               "type":"user",
               "id":"1"
            }
         },
        "comments": {
            "data": [
                {
                    "type": "comment",
                    "id": "1000"
                }
            ]
        }
      }
   },
   "included":[
      {
         "type":"user",
         "id":"1",
         "attributes":{
            "name":"Post Author"
         },
         "links":{
            "self":{
               "href":"http://example.com/users/1"
            },
            "friends":{
               "href":"http://example.com/users/1/friends"
            },
            "comments":{
               "href":"http://example.com/users/1/comments"
            }
         }
      },
      {
         "type":"user",
         "id":"2",
         "attributes":{
            "name":"Barristan Selmy"
         },
         "links":{
            "self":{
               "href":"http://example.com/users/2"
            },
            "friends":{
               "href":"http://example.com/users/2/friends"
            },
            "comments":{
               "href":"http://example.com/users/2/comments"
            }
         }
      },
      {
         "type":"comment",
         "id":"1000",
         "attributes":{
            "dates":{
               "created_at":"2015-07-18T12:13:00+00:00",
               "accepted_at":"2015-07-19T00:00:00+00:00"
            },
            "comment":"Have no fear, sers, your king is safe."
         },
         "relationships":{
            "user":{
               "data":{
                  "type":"user",
                  "id":"2"
               }
            }
         },
         "links":{
            "self":{
               "href":"http://example.com/comments/1000"
            }
         }
      }
   ],
   "links":{
      "self":{
         "href":"http://example.com/posts/9"
      },
      "first":{
         "href":"http://example.com/posts/1"
      },
      "next":{
         "href":"http://example.com/posts/10"
      },
      "comments":{
         "href":"http://example.com/posts/9/comments"
      }
   },
   "meta":{
      "author":{
         "name":"Nil Portugués Calderó",
         "email":"contact@nilportugues.com"
      },
      "is_devel":true
   },
   "jsonapi":{
      "version":"1.0"
   }
}
JSON;
        $post = HelperFactory::complexPost();

        $transformer = new JsonApiTransformer($mapper);
        $transformer->setMeta(
            [
                'author' => [
                    'name' => 'Nil Portugués Calderó',
                    'email' => 'contact@nilportugues.com',
                ],
            ]
        );
        $transformer->addMeta('is_devel', true);
        $transformer->setSelfUrl('http://example.com/posts/9');
        $transformer->setFirstUrl('http://example.com/posts/1');
        $transformer->setNextUrl('http://example.com/posts/10');

        $this->assertEquals(
            \json_decode($expected, true),
            \json_decode((new JsonApiSerializer($transformer))->serialize($post), true)
        );
    }
```

**Comment by nilportugues** [comment]
Fixed

**Comment by OskarD** [comment]
I don't think this solves the second part of the issue:

> Another problem, and bigger, is than the output of the relationships node must match with the nature of the relation, for example, if the model has a relation with belongsTo, the output always will be a property data as an object (not an array) with the type and id properties of the relation:
> Example: 
> "relationships": { "company": { "data": { "type": "companies", "id": "1" } },...etc
> 
> If the relaion is multiple record (such a hasMany) the output allwais have to be an array (also if the query only returns one object)
> Example:
> { "relationships": { "platforms": { "data": [ { "type": "platforms", "id": "1" } ] }...etc
> 
> OR
>  {"relationships": { "platforms": { "data": [ { "type": "platforms", "id": "1" }, { "type": "platforms", "id": "2" } ] }...etc
> 
> You can see the specification here:
> http://jsonapi.org/format/#fetching-relationships

**Comment by rmarinleal** [comment]
Hello,

Sorry for not answer before, we are having many perfomance problems with the jsonapi's standard and the implementation of it with this library.

When diving in the code, I can say it's a good idea in theory, but when you apply the library to a database with several relations (for example, one object have 5 belongs and 7 hasmany relations) the output can easyly make more than 200 petitions to the Database, it'll be increased when you ask for a list of models (in a database with 40 tables and less than 20k records, wich I consider a vary small database you will get an out of memory in all petitions).

We are working in changing the library's idea, implementing the query with "joins" instead of using single gets of models, but it's a hard work.

If at last we obtain a good result, I'll comment it to you.

Thanks for answer and your patient

**Comment by nilportugues** [comment]
@rmarinleal feedback and examples based on your edge case are welcomed :+1:

**Comment by directrix1** [comment]
This bug has not been fixed. It just shifted from working only with belongsTo relationships to only working with hasMany relationships.

**Comment by nilportugues** [comment]
@directrix1 would help if you provide a fix or code
