### ISSUE TITLE
"included" parameter

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#61]
According to the [JSON API documentation](http://jsonapi.org/format/#fetching-includes), the parameter "included" should be "include".

In [this package's documentation](https://github.com/nilportugues/laravel5-jsonapi) there is a definition that looks like this 

> &include=resource1
&include=resource1.resource2,resource2.resource3

But then it says this (Note the difference in bold)

> For instance, /employees?include**d**=order will only load order type data inside included member, but /employees?include**d**=order.employee will only load those orders related to the employee type.

Using `include` will trigger a `QueryException`, `included` does not - however I'm not sure it works as it should. I seem to be getting all relationships even though I only try to get one of them using something like `included=one_relation`.

From JSON API doc:

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

**Comment by nilportugues** [comment]
Indeed it's a bug in the documentation... this is one quick fix.

**Comment by OskarD** [comment]
The functionality does not follow the spec either


Skickat från min Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Originalmeddelande --------</div><div>Från: Nil Portugués Calderó <notifications@github.com> </div><div>Datum: 2016-05-03  11:59  (GMT+01:00) </div><div>Till: nilportugues/laravel5-jsonapi <laravel5-jsonapi@noreply.github.com> </div><div>Kopia: Oskar Danielsson <oskar.danielsson@hotmail.com>, Author <author@noreply.github.com> </div><div>Rubrik: Re: [nilportugues/laravel5-jsonapi] "included" parameter (#61) </div><div>
</div>
Indeed it's a bug in the documentation... this is one quick fix.

---

**Comment by nilportugues** [comment]
I do believe it follows the spec, maybe it's related to this bug.

**Comment by OskarD** [comment]
The code accepts "included" instead of "include", but it doesn't do anything when used. Or am I missing something here?

**Comment by OskarD** [comment]
I have done some more testing and it seems like there are only these two problems:

1. The doc is inaccurate (included instead of include)
2. Using "include" without any options throws a QueryException (I think it would be better if it just didn't include anything)

"included" does not make any difference, as intended, and "include=" with an actual relation works as it should

**Comment by OskarD** [comment]
I have started a discussion [on the json api forums](http://discuss.jsonapi.org/t/how-can-i-not-include-any-relationships/456) and so far I do not know what the official convention is, but I would prefer an implementation where relationships are not loaded by default

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.2.0

**Comment by OskarD** [comment]
Actually, since you never commented on that part I never implemented the default behavior change. I will do it now, because I think it would be helpful :)
