### ISSUE TITLE
Pivot data is not translated into the response

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#63]
If a class has something like this:
```
public function someModel()
{
    return $this->belongsToMany(SomeModel::class)->withPivot('foo');
}
```
then an object (As an array) will look something like this:

```
[
    'id' => int 7
    'pivot' => [
          'this_class_id' => 1
          'some_model_id' => 7
          'foo' => 'bar'
     ]
```

The additional `foo` value is not returned in the response, so it is just completely lost.

I don't know how it should be implemented with the JSON API standard, but I hope we can figure out some way :)

**Comment by OskarD** [comment]
Maybe this is how it should be returned?

```
"relationships": {
      "some_models": {
        "data": [
          {
            "type": "some_model",
            "id": "1",
            "type": "A type"
          }
        ]
      }
    }
```
or
```
"relationships": {
      "some_models": {
        "data": [
          {
            "type": "some_model",
            "id": "1",
            "pivot": [
              "type": "A type"
            ]
          }
        ]
      }
    }
```

Thoughts?

**Comment by nilportugues** [comment]
@OskarD  Must be second option because we cannot have 2 types in the same json object

**Comment by OskarD** [comment]
@nilportugues "type" was a bad example, I have changed it to foo so it makes more sense. 

But I guess it was also a good example, because now we can see why the first solution won't work. I suggest we implement the second one (With a `pivot`-key inside `data`)

**Comment by nilportugues** [comment]
Second still for me. I agree @OskarD

**Comment by OskarD** [comment]
@nilportugues which component should handle this? Is it php-api-transformer?

**Comment by nilportugues** [comment]
"Pivot" should be "attributes". It's just another object in the end... you're actually fetching a new object so api-transformer. 

Work from the https://github.com/nilportugues/php-api-transformer/tree/1.5.1 tag. 

As 2.x will be PHP7 only. I intend to support 5.6 and 1.x. No worries.

**Comment by nilportugues** [comment]
@OskarD I'm actually brushing up rough edges in the API Transformer projects for a major release sometime this summer with fixes for all bugs reported that have not been solved.

**Comment by OskarD** [comment]
@nilportugues Are you sure about the name of the field (attributes)? I feel like it might be confusing when loading the model and getting it together with the other attributes, as if it belonged to the original resource. Wouldn't it be better to have them inside a pivot field?
