### ISSUE TITLE
Possible to use without Laravel?

### ISSUE THREAD

**Issue by mtangoo** [nilportugues/laravel5-jsonapi#64]
Hi,
I use Eloquent models but I use homegrown framework so I don't use Laravel per se.
Can I still use your package?

**Comment by nilportugues** [comment]
@mtangoo yes it is, you're looking for this: https://github.com/nilportugues/php-json-api

**Comment by mtangoo** [comment]
I already use Symfony's HTTPFoundation to handle HTTP. can you help me understand how I can put that together? Should I open an issue in that specific repo?

**Comment by nilportugues** [comment]
@mtangoo using Symfony? Then how about using the Symfony version https://github.com/nilportugues/symfony-jsonapi ?

**Comment by nilportugues** [comment]
@mtangoo under the hood all uses PSR7 Response objects. Using the Symfony version, that requires the symfony psr7 bridge , will get all the problems solved for you.

**Comment by mtangoo** [comment]
>using Symfony?
 
No. I use Symfony's HttpFoundation to power my Request/Response on my framework. So I was wondering how to go about.

> Using the Symfony version, that requires the symfony psr7 bridge , will get all the problems solved for you.

Can you explain this?

**Comment by nilportugues** [comment]
@mtangoo yeah open issue on the https://github.com/nilportugues/php-json-api

**Comment by mtangoo** [comment]
cool thanks. I will do that
