### ISSUE TITLE
JSON columns being filtered out by DataAttributesHelper

### ISSUE THREAD

**Issue by martinmike2** [nilportugues/laravel5-jsonapi#67]
Given a JSONB column named 'settings' with the following structure: 
```
{
"dates":[
{"name": "Test Date", "value": "2016-11-24 00:00:00"},
{"name": "Test 2", "value": "2016-12-01 00:00:00"}
]
}
```
the settings attribute does not appear in the output.

Model:

```
class Client extends Model
{
    protected $table = 'clients';
     
    protected $guarded = ['*'];
    
    protected $fillable = [
        'name',
        'settings'
    ];
    
    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    protected $casts = [
        'settings' => 'json'
    ];

    protected $default_settings = [
          "dates" => [
              [
                  'name' => 'Thanksgiving Break',
                  'value' => '2016-11-24 00:00:00'
              ]
          ]
    ];
}


```

Transformer:

```
class ClientTransformer implements JsonApiMapping
{

    /**
     * Returns a string with the full class name, including namespace.
     *
     * @return string
     */
    public function getClass()
    {
        return Client::class;
    }

    /**
     * Returns a string representing the resource name as it will be shown after the mapping.
     *
     * @return string
     */
    public function getAlias()
    {
        return 'client';
    }

    /**
     * Returns an array of properties that will be renamed.
     * Key is current property from the class. Value is the property's alias name.
     *
     * @return array
     */
    public function getAliasedProperties()
    {
        return [];
    }

    /**
     * List of properties in the class that will be ignored by the mapping.
     *
     * @return array
     */
    public function getHideProperties()
    {
        return [
            'created_at',
            'updated_at'
        ];
    }

    /**
     * Returns an array of properties that are used as an ID value.
     *
     * @return array
     */
    public function getIdProperties()
    {
        return ['id'];
    }

    /**
     * Returns a list of URLs. This urls must have placeholders to be replaced with the getIdProperties() values.
     *
     * @return array
     */
    public function getUrls()
    {
        return [
            'self' => ['name' => 'clients.show', 'as_id' => 'id'],
            'clients' => ['name' => 'clients.index']
        ];
    }

    /**
     * Returns an array containing the relationship mappings as an array.
     * Key for each relationship defined must match a property of the mapped class.
     *
     * @return array
     */
    public function getRelationships()
    {
        return [];
    }
}

```

**Comment by nilportugues** [comment]
@martinmike2 looks like I'm missing something due to the JSONB fields. Need to dig in to see where did Eloquent handle the JSONB data and go for it and fetch it.

**Comment by martinmike2** [comment]
Just for some more information, I was able to manipulate the JSON Object to get it into the output.

I had to use this structure to get it to work:
`{
    "setting": {
        "data": [
            {
                "start": "2016-01-01 00:00:00",
                "end": "2017-01-01 00:00:00", 
                "name": "Test Setting", 
                "type": "date"
            }
        ]
    }
}`

**Comment by jeremymlane** [comment]
I can confirm this bug. The function that seems causing the problem is: `DataAttributesHelper::containsClassIdentifierKey()`.

If the last element in the JSON object is a string, then it works, but if the last element is another JSON object, it's filtered out.

For example, this works: 

`{
  "menus": {
    "primary_menu": {
      "name": "Top Menu",
      "menu_id": 123,
      "options": [],
      "description": "This menu is displayed at the top of every page."
    },
    "secondary_menu": {
      "name": "Footer Menu",
      "menu_id": 1,
      "options": [],
      "description": "This menu is displayed in the footer of every page."
    },
    "another": "string value"
  }
}`

But this doesn't: 

`{
  "menus": {
    "primary_menu": {
      "name": "Top Menu",
      "menu_id": 123,
      "options": [],
      "description": "This menu is displayed at the top of every page."
    },
    "secondary_menu": {
      "name": "Footer Menu",
      "menu_id": 1,
      "options": [],
      "description": "This menu is displayed in the footer of every page."
    }
  }
}`

**Comment by nilportugues** [comment]
@jeremymlane precise description will certainly help! good

**Comment by nilportugues** [comment]
@jeremymlane mind using this version of the containsClassIdentifierKey method and letting me know if it fixes the issue? 

```php
  /**
     * @param array $input
     * @param bool  $foundIdentifierKey
     *
     * @return bool
     */
    protected static function containsClassIdentifierKey(array $input, $foundIdentifierKey = false)
    {
        if (!is_array($input)) {
            return false;
        }

        if (\in_array(Serializer::CLASS_IDENTIFIER_KEY, $input, true)) {
            return true;
        }

        if (!empty($input[Serializer::SCALAR_VALUE])) {
            $input = $input[Serializer::SCALAR_VALUE];

            if (\is_array($input)) {
                foreach ($input as $value) {
                    if (\is_array($value)) {
                        $foundIdentifierKey = $foundIdentifierKey
                            || self::containsClassIdentifierKey($value, $foundIdentifierKey);
                    }
                }
            }
        }

        return !$foundIdentifierKey;
    }
```

**Comment by jeremymlane** [comment]
@nilportugues No go. From what I can tell the problem may be with the foreach loop, but I don't know for sure.

**Comment by nilportugues** [comment]
@jeremymlane https://github.com/nilportugues/php-json-api/blob/23d48aae51b842fd4454aba632b73b85f0896873/src/Helpers/DataAttributesHelper.php#L117 Hmm I believe removing the ` && empty($mappings[$value[Serializer::SCALAR_TYPE]])` will fix this. 

Mind trying again?

**Comment by jeremymlane** [comment]
@nilportugues Still nothing. However, removing this conditional fixes it: 

https://github.com/nilportugues/php-json-api/blob/23d48aae51b842fd4454aba632b73b85f0896873/src/Helpers/DataAttributesHelper.php#L123

**Comment by nilportugues** [comment]
@jeremymlane lemme fix the underlying lib and I'll provide a minor fix.

I'll let you know in a bit

**Comment by nilportugues** [comment]
@jeremymlane https://gist.github.com/nilportugues/4dbeb21a9060c87d19d1623aa97a8dc6 mind testing again?

I don't want to do release until we can keep all functionalities OK

**Comment by jeremymlane** [comment]
@nilportugues Wish I could say it was working, but still have the same issue. If I remove this conditional it works: 

https://gist.github.com/nilportugues/4dbeb21a9060c87d19d1623aa97a8dc6#file-dataattributeshelper-php-L123

**Comment by nilportugues** [comment]
@jeremymlane https://gist.github.com/nilportugues/48728e70272be3ae5f0960d43fa11ee4

**Comment by jeremymlane** [comment]
@nilportugues Bingo. That did it.

**Comment by nilportugues** [comment]
RELEASING RIGHT NOW,  :dancer:

**Comment by jeremymlane** [comment]
Sweet! Thanks for you help!

**Comment by nilportugues** [comment]
`composer update nilportugues/json-api` will do. Release 2.2.3 comes with the fix. 

@jeremymlane now I can go to sleep happily. Thanks, this has been great teamwork :)
