### ISSUE TITLE
Cannot use custom request

### ISSUE THREAD

**Issue by andrewboy** [nilportugues/laravel5-jsonapi#68]
At now I cannot use custom Request in the controller to validate the incoming data.

**Comment by nilportugues** [comment]
@andrewboy can you please develop? Sample code would be awesome

**Comment by andrewboy** [comment]
So the problem is that I cannot inject overwritten Request class to the inherited NilPortugues\Laravel5\JsonApi\Controller\JsonApiControllers' method, because the parent class method already got an injection and this case I have to use that existed class per moment.

**CustomRequest** not works:

```
namespace NilPortugues\Laravel5\JsonApi\Controller;

...

trait JsonApiTrait
{

    ...

    /**
     * Post Action.
     *
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function store(**CustomRequest** $request)
    {
        ...
    }

    ...
}
```

Please develop? What do you mean? Fork the project and implement this?

Best regards,
Andrew

**Comment by nilportugues** [comment]
If `CustomRequest` extends from `Illuminate\Http\Request` you should have no problem at all. Is this the case? 

Your problem is you changed the signature of the method, I believe this is causing an error. 

```
 Declaration of MembersController::store(CustomRequest $request) should be compatible with NilPortugues\Laravel5\JsonApi\Controller\JsonApiController::store(Illuminate\Http\Request $request) 
```

This cannot be done. Yet you can pass in your request object.

**Comment by andrewboy** [comment]
But it's not gonna work with that way, no matter you extend from the `Illuminate\Http\Request`, you have to use the same class you inject. I tried it.
If this would work, my CustomRequest would work either. 

`CustomRequest `
extends 
`App\Http\Requests\Request `
extends 
`Illuminate\Foundation\Http\FormRequest `
extends 
`Illuminate\Foundation\Http `
extends 
`Illuminate\Http\Request `
extends 
`Symfony\Component\HttpFoundation\Request`
