### ISSUE TITLE
Json API Response class occures incompatibility reasons

### ISSUE THREAD

**Issue by andrewboy** [nilportugues/laravel5-jsonapi#69]
Because the package Response classes not extended from `\Symfony\Component\HttpFoundation\Response`, the usability is limited.

**Comment by nilportugues** [comment]
Response uses PSR7. This does not limit the usability, but actually the opposite. 

If you want to use Symfony's, use the bridge: http://symfony.com/doc/current/cookbook/psr7.html : It's already included by this package.
