### ISSUE TITLE
Creating resources with relations ignores relations

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#71]
An example of creating a resource with a relation can be found here: http://jsonapi.org/format/#crud-creating 
```
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```
In this example, a relationship between the newly created `photos` resource and an existing `photographer` should be created. This is not the case, at least with many-to-many relations (That's all I've tested).

With the current implementation, the `photos` resource is created without the relation.

**Comment by nilportugues** [comment]
@OskarD This is eloquent related once again. 

Looks like editing https://github.com/nilportugues/laravel5-jsonapi/blob/master/src/NilPortugues/Laravel5/JsonApi/Actions/CreateResource.php and overriding the CreateResource

**Comment by nilportugues** [comment]
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.3.0 may fix this. Mind checking?

**Comment by OskarD** [comment]
Sorry @nilportugues I had to abandon the library to make a deadline :( I will let you know if I get the chance to pick it up again!

**Comment by nilportugues** [comment]
@OskarD no problem

**Comment by nilportugues** [comment]
BTW did you ever try https://github.com/nilportugues/laravel5-jsonapi#postputpatch-with-relationships ? 
It's the way to do it.
