### ISSUE TITLE
Mutators returning arrays result in 'Undefined index: @type' error

### ISSUE THREAD

**Issue by jeremymlane** [nilportugues/laravel5-jsonapi#73]
Sorry to give you another bug. Assuming the model: 

```
class PageGroup extends Model
{

    protected $appends = ['layout_settings'];

    public function getLayoutSettingsAttribute(){
        return ['test'=>'My Test Array'];
    }

}
```

I'm getting an `Undefined index: @type` error when trying to use the api. If I change getLayoutSettingsAttribute() to: 

```
public function getLayoutSettingsAttribute(){
    return 'My Test String';
}
```

Everything works fine.

**Comment by nilportugues** [comment]
@jeremymlane mind checking the version used for nilportugues/json-api and nilportugues/laravel5-json-api?  Also, mind sharing the line throwing that error? 

I'm sure it can be fixed quite easily.

**Comment by nilportugues** [comment]
Does https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.3.0 fix this? I believe it should.

**Comment by jeremymlane** [comment]
@nilportugues That did it. Seems to be working now. I had nilportugues/json-api@2.1.14 and dev-master of laravel-json-api before I updated, but can't recall the line number.

**Comment by nilportugues** [comment]
@jeremymlane thanks for the feedback :+1:
