### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by mspiderv** [nilportugues/laravel5-jsonapi#76]
I installed fresh Laravel 5.2.38, created entity "content-type", seeded 100 records and installed this JSON API implementation. When I open http://127.0.0.1/api/content-types in my browser, I'm getting [this response](http://pastebin.com/GLgFqPpc).

As you can see here
`"page":{
         "total":100,
         "last":10,
         "number":1,
         "size":10
      }`
I have 100 records of "content-type" entity. That's correct. But there are 15 records in "data" attribute of response. Not 10.

When I open http://127.0.0.1/api/content-types?page[size]=10 it is correct.

What URL should I open to see all 100 records ? http://127.0.0.1/api/content-types?page[size]=100 works, but frontend application does not know there are exactly 100 records. It just wants all of them.

**Comment by nilportugues** [comment]
@mspiderv can you tell me which version of this package you're using? `2.4.0` ? `2.4.1`? 

I'm thinking 2.4.1 brought in a bug.

**Comment by mspiderv** [comment]
@nilportugues I'm using 2.4.0. I think the problem is the default Laravel's pagination page size is 15 and your default value in `NilPortugues\Laravel5\JsonApi\Controller\JsonApiTrait` on line 34 is 10 not 15.

**Comment by nilportugues** [comment]
Alright, thanks for pointing this out. I can now check :+1:

**Comment by yurykabanov** [comment]
Now you can check a PR #87 :)

**Comment by nilportugues** [comment]
@yurykabanov Thank you very much!
