### ISSUE TITLE
Update a resource with relationships

### ISSUE THREAD

**Issue by alexjoffroy** [nilportugues/laravel5-jsonapi#77]
I followed the example described in the readme to create a resource with attached relationships, and it works well. 

The doc said that we could do the same on update but it doesn't seem to work.

Looking more closely, I think that we should add $data in get method from PatchResource and PutResource : 
```php
    public function get($id, array $data, $className, callable $findOneCallable, callable $update)
    {
        try {
            DataObject::assertPut($data, $this->serializer, $className, $this->errorBag);

            $model = $findOneCallable();

            if (empty($model)) {
                $mapping = $this->serializer->getTransformer()->getMappingByClassName($className);

                return $this->resourceNotFound(new ErrorBag([new NotFoundError($mapping->getClassAlias(), $id)]));
            }
            $values = DataObject::getAttributes($data, $this->serializer);
            $update($model, $data, $values, $this->errorBag);

            $response = $this->resourceUpdated($this->serializer->serialize($model));
        } catch (Exception $e) {
            $response = $this->getErrorResponse($e);
        }

        return $response;
    }
```

And of course add the same on JsonApiTrait:

```php
    protected function updateResourceCallable()
    {
        return function (Model $model, $data, array $values, ErrorBag $errorBag) {
            foreach ($values as $attribute => $value) {
                $model->$attribute = $value;
            }
            try {
                $model->update();
            } catch (\Exception $e) {
                $errorBag[] = new Error('update_failed', 'Could not update resource.');
                throw $e;
            }
        };
    }
```

With this we can access $data in updateResourceCallable like in createResourceCallable, and we can access relationships.

What do you think about it ? I will make a PR later.

**Comment by nilportugues** [comment]
Can you provide a test too? I'm willing to merge this PR :)

**Comment by alexjoffroy** [comment]
Which test case am I supposed to do ? I did not see any case for update in `JsonApiControllerTest.php`.

Other point: I will also need to make a PR on https://github.com/nilportugues/php-json-api as `PatchResource.php` and `PutResource.php` are parts of this package :)

**Comment by nilportugues** [comment]
Write a new one @alexjoffroy. Provide one where you actually access to $data in updateResourceCallable :)

**Comment by alexjoffroy** [comment]
OK. I'll do it as soon as possible !
