### ISSUE TITLE
Problem with collections

### ISSUE THREAD

**Issue by vanitom** [nilportugues/laravel5-jsonapi#84]
Hello,

I tested this package. Using the example, I detected an error with respect to JSONAPI specifications.

With the following query `/employees/10`, this is what I get:
```
{
  "data": {
    "type": "employee",
    "id": "10",
    "attributes": {
      "address": "343 Friary Road",
      "business_phone": "0118 9843212",
      "city": "Manchester",
      [...]
      "web_page": null,
      "zip_postal_code": "M3 3DL"
    },
    "links": {
      "self": {
        "href": "http://api.dev-forms/employees/10"
      },
      "employee_orders": {
        "href": "http://api.dev-forms/employees/10/orders"
      }
    },
    "relationships": {
      "latest_orders": {
        "data": [
          {
            "type": "order",
            "id": "82"
          }
        ]
      }
    }
  },
  "included": [
    {
      "type": "order",
      "id": "82",
      "attributes": {
        "employee_id": "10",
        "customer_id": null,
        [...]
        "status_id": "0"
      },
      "links": {
        "self": {
          "href": "http://api.dev-forms/orders/82"
        },
        "employee": {
          "href": "http://api.dev-forms/employees/10"
        }
      }
    }
  ],
  "links": {
    "employees": {
      "href": "http://api.dev-forms/employees"
    },
    "employee_orders": {
      "href": "http://api.dev-forms/employees/10/orders"
    },
    "self": {
      "href": "http://api.dev-forms/employees/10"
    }
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```
It's perfect.

Here is what I get with the following query `/employees`:
```
{
  "data": [
    {
      "id": 10,
      "company": "Acme Industries",
      "last_name": "Smith",
      "first_name": "Mike",
      "email_address": "mike.smith@mail.com",
      "job_title": "Horticultarlist",
      "business_phone": "0118 9843212",
      "home_phone": null,
      "mobile_phone": null,
      "fax_number": null,
      "address": "343 Friary Road",
      "city": "Manchester",
      "state_province": "Lancs.",
      "zip_postal_code": "M3 3DL",
      "country_region": "United Kingdom",
      "web_page": null,
      "notes": null,
      "attachments": null,
      "full_name": "Mike Smith"
    }
  ],
  "included": [],
  "links": {
    "self": {
      "href": "http://api.dev-forms/employees?page[number]=1&page[size]=10"
    },
    "first": {
      "href": "http://api.dev-forms/employees?page[number]=1&page[size]=10"
    },
    "last": {
      "href": "http://api.dev-forms/employees?page[number]=1&page[size]=10"
    }
  },
  "meta": {
    "page": {
      "total": 1,
      "last": 1,
      "number": 1,
      "size": 10
    }
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```
This does not match the specifications. We should get the same format as the previous one with the "type", the "attributes", ...

Is this normal?

Best regards

**Comment by nilportugues** [comment]
@vanitom hmmm mind checking if the model has been mapped? I think that may be the issue. 

otherwise I need to investigate further.

**Comment by Robindfuller** [comment]
I have the same problem after following your instructions.

**Comment by nilportugues** [comment]
@Robindfuller thanks for the feedback, let me look into it.

**Comment by Robindfuller** [comment]
I'm pretty keen to get this working :-). I've tracked the problem down to ListResource.php . On line 80 you have ...

    $results = $resultsCallable();

    if ($results instanceof Collection) {
        $results = json_encode(['data' => $results->toArray()]);
    }

It basically bypasses any transformation -- accept the collection's 'toArray()' method. For now, I can only get it working replacing it with the following...

    $so = $this->serializer;
    $results = $resultsCallable()->map(function($model) use ($so){
        return $data = json_decode($so->serialize($model))->data;
    });

    if ($results instanceof Collection) {
        $results = json_encode(['data' => $results->toArray()]);
    }

Its a shameful hack so I haven't submitted a pull request but I'd hoped that it helps you to find the problem.

**Comment by Robindfuller** [comment]
I just removed the overriding 'get' method from NilPortugues\Laravel5\JsonApi\Actions\ListResource and it works fine now.

**Comment by vanitom** [comment]
Thank you ! it works perfectly well now.
