### ISSUE TITLE
ErrorException in MappingFactory.php line 91:

### ISSUE THREAD

**Issue by patayko** [nilportugues/laravel5-jsonapi#90]
Argument 1 passed to NilPortugues\Api\Mapping\MappingFactory::fromArray() must be of the type array, string given, called in E:\xampp\htdocs\local-domain\market-service\vendor\nilportugues\laravel5-json-api\src\NilPortugues\Laravel5\JsonApi\Mapper\Mapper.php on line 24 and defined.

Also tried to edit the file from the source. It seemed that the files is not loaded.

**Comment by victorsferreira** [comment]
Did you manage to make it work @patayko ?
