### ISSUE TITLE
Do you plan on implementing error handling?

### ISSUE THREAD

**Issue by malhal** [nilportugues/laravel5-jsonapi#92]
Hi just wondering if you plan on implementing the [error handling part of the JSON API](http://jsonapi.org/format/#errors) spec? Where you would render all exceptions to the JSON errors dictionary and a suitable http code.

Apologies if you already do I just didn't see it mentioned in the Readme or when I briefly looked over the code.

**Comment by nilportugues** [comment]
@malhal Actually it's implemented... I got to admit it requires better documentation.
