### ISSUE TITLE
No mappings were found. Mappings are required by the transformer to work.

### ISSUE THREAD

**Issue by shermaza** [nilportugues/laravel5-jsonapi#94]
I'm getting the error `No mappings were found. Mappings are required by the transformer to work.` when I try to hit the route /users/1.

I've created a jsonapi.php file with the contents:
```
<?php
use App\Model\Api\UsersTransformer;

return [
    UsersTransformer::class,
];
```

Let me know if I need to include anything else.

**Comment by Stubbs** [comment]
Did you find the answer @shermaza ?

**Comment by shermaza** [comment]
@Stubbs I apologize, I do not remember how I fixed this issue. However, my gut says that I had some mis-configured models or migrations in my project, or some other typo that I didn't originally detect. I would recommend re-examining each of your entities from migration -> model -> transformer -> controller and make sure nothing is mis-typed, named incorrectly, etc.
